name: CI
on: [pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: ['1.16', '1.17', '1.18', '1.19', '1.20']

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=.golangci.yaml"
          reporter: github-pr-review
          go_version: ${{ matrix.go }}
          cache: false # managed by actions/setup-go

      - name: Tests
        run: make tests
        env:
          WITH_COVERAGE: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: ${{ matrix.go }} == '^1.20'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt

  doc:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: ./doc/
          config_file: .markdownlint.json

      - uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review
          locale: "US"
          exclude: |
            ./vendor/*

      - name: alexjs
        uses: reviewdog/action-alex@v1
        with:
          workdir: ./doc/
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning