name: Release

on:
  pull_request:
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.10'

      - name: Tag
        id: tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: tar -czvf grabana-${{ steps.tag.outputs.tag }}-linux-64bit.tar.gz ./grabana

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: grabana-${{ steps.tag.outputs.tag }}-linux-64bit.tar.gz
          asset_name: grabana-${{ steps.tag.outputs.tag }}-linux-64bit.tar.gz
          tag: ${{ steps.tag.outputs.tag }}
          overwrite: true
