name: Release

on:
  pull_request:
    types: closed

jobs:
  tag:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.tag.outputs.tag }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Tag
        id: tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}

  goreleaser:
    runs-on: ubuntu-latest
    needs: [tag]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version:  latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
          GORELEASER_CURRENT_TAG: ${{ needs.tag.outputs.version }}
